=== rwfazul/nodejs-xml/services/files/notas.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT IE (#PCDATA)>
<!ELEMENT UF (#PCDATA)>
<!ELEMENT CEP (#PCDATA)>
<!ELEMENT CPF (#PCDATA)>
<!ELEMENT CRT (#PCDATA)>
<!ELEMENT CST (#PCDATA)>
<!ELEMENT IPI (cEnq, IPINT)>
<!ELEMENT NCM (#PCDATA)>
<!ELEMENT NFe (infNFe, Signature)>
<!ATTLIST NFe
	xmlns CDATA #FIXED "http://www.portalfiscal.inf.br/nfe"
>
<!ELEMENT PIS (PISAliq | PISNT)>
<!ELEMENT cDV (#PCDATA)>
<!ELEMENT cNF (#PCDATA)>
<!ELEMENT cUF (#PCDATA)>
<!ELEMENT det (prod, imposto, infAdProd?)>
<!ATTLIST det
	nItem CDATA #REQUIRED
>
<!ELEMENT esp (#PCDATA)>
<!ELEMENT ide (cUF, cNF, natOp, indPag, mod, serie, nNF, dEmi, tpNF, cMunFG, tpImp, tpEmis, cDV, tpAmb, finNFe, procEmi, verProc)>
<!ELEMENT mod (#PCDATA)>
<!ELEMENT nNF (#PCDATA)>
<!ELEMENT nro (#PCDATA)>
<!ELEMENT vBC (#PCDATA)>
<!ELEMENT vII (#PCDATA)>
<!ELEMENT vNF (#PCDATA)>
<!ELEMENT vST (#PCDATA)>
<!ELEMENT vol (qVol, esp?, pesoL, pesoB)>
<!ELEMENT CFOP (#PCDATA)>
<!ELEMENT CNPJ (#PCDATA)>
<!ELEMENT ICMS (ICMS60 | ICMS00)>
<!ELEMENT cEAN (#PCDATA)>
<!ELEMENT cEnq (#PCDATA)>
<!ELEMENT cMun (#PCDATA)>
<!ELEMENT dEmi (#PCDATA)>
<!ELEMENT dest (CPF, xNome, enderDest, IE, email)>
<!ELEMENT emit (CNPJ, xNome, xFant, enderEmit, IE, CRT)>
<!ELEMENT fone (#PCDATA)>
<!ELEMENT orig (#PCDATA)>
<!ELEMENT pPIS (#PCDATA)>
<!ELEMENT prod (cProd, cEAN, xProd, NCM, CFOP, uCom, qCom, vUnCom, vProd, cEANTrib, uTrib, qTrib, vUnTrib, vFrete?, indTot)>
<!ELEMENT qCom (#PCDATA)>
<!ELEMENT qVol (#PCDATA)>
<!ELEMENT tpNF (#PCDATA)>
<!ELEMENT uCom (#PCDATA)>
<!ELEMENT vIPI (#PCDATA)>
<!ELEMENT vPIS (#PCDATA)>
<!ELEMENT vSeg (#PCDATA)>
<!ELEMENT xCpl (#PCDATA)>
<!ELEMENT xLgr (#PCDATA)>
<!ELEMENT xMun (#PCDATA)>
<!ELEMENT IPINT (CST)>
<!ELEMENT PISNT (CST)>
<!ELEMENT cPais (#PCDATA)>
<!ELEMENT cProd (#PCDATA)>
<!ELEMENT cStat (#PCDATA)>
<!ELEMENT chNFe (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT modBC (#PCDATA)>
<!ELEMENT nProt (#PCDATA)>
<!ELEMENT natOp (#PCDATA)>
<!ELEMENT pICMS (#PCDATA)>
<!ELEMENT pesoB (#PCDATA)>
<!ELEMENT pesoL (#PCDATA)>
<!ELEMENT qTrib (#PCDATA)>
<!ELEMENT serie (#PCDATA)>
<!ELEMENT total (ICMSTot)>
<!ELEMENT tpAmb (#PCDATA)>
<!ELEMENT tpImp (#PCDATA)>
<!ELEMENT uTrib (#PCDATA)>
<!ELEMENT vBCST (#PCDATA)>
<!ELEMENT vDesc (#PCDATA)>
<!ELEMENT vICMS (#PCDATA)>
<!ELEMENT vProd (#PCDATA)>
<!ELEMENT xFant (#PCDATA)>
<!ELEMENT xNome (#PCDATA)>
<!ELEMENT xPais (#PCDATA)>
<!ELEMENT xProd (#PCDATA)>
<!ELEMENT COFINS (COFINSAliq | COFINSNT)>
<!ELEMENT ICMS00 (orig, CST, modBC, vBC, pICMS, vICMS)>
<!ELEMENT ICMS60 (orig, CST, vBCSTRet, vICMSSTRet)>
<!ELEMENT cMunFG (#PCDATA)>
<!ELEMENT digVal (#PCDATA)>
<!ELEMENT finNFe (#PCDATA)>
<!ELEMENT indPag (#PCDATA)>
<!ELEMENT indTot (#PCDATA)>
<!ELEMENT infCpl (#PCDATA)>
<!ELEMENT infNFe (ide, emit, dest, entrega?, det+, total, transp, infAdic)>
<!ATTLIST infNFe
	versao CDATA #FIXED "2.00"
	Id CDATA #REQUIRED
>
<!ELEMENT tpEmis (#PCDATA)>
<!ELEMENT transp (modFrete, transporta?, vol)>
<!ELEMENT vFrete (#PCDATA)>
<!ELEMENT vOutro (#PCDATA)>
<!ELEMENT vUnCom (#PCDATA)>
<!ELEMENT xEnder (#PCDATA)>
<!ELEMENT ICMSTot (vBC, vICMS, vBCST, vST, vProd, vFrete, vSeg, vDesc, vII, vIPI, vPIS, vCOFINS, vOutro, vNF)>
<!ELEMENT KeyInfo (X509Data)>
<!ELEMENT PISAliq (CST, vBC, pPIS, vPIS)>
<!ELEMENT entrega (CPF, xLgr, nro, xCpl, xBairro, cMun, xMun, UF)>
<!ELEMENT imposto (ICMS, IPI?, PIS, COFINS)>
<!ELEMENT infAdic (infCpl)>
<!ELEMENT infProt (tpAmb, verAplic, chNFe, dhRecbto, nProt, digVal, cStat, xMotivo)>
<!ELEMENT nfeProc (NFe, protNFe)>
<!ATTLIST nfeProc
	versao CDATA #FIXED "2.00"
	xsi:schemaLocation CDATA #IMPLIED
	xmlns CDATA #FIXED "http://www.portalfiscal.inf.br/nfe"
	xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
>
<!ELEMENT pCOFINS (#PCDATA)>
<!ELEMENT procEmi (#PCDATA)>
<!ELEMENT protNFe (infProt)>
<!ATTLIST protNFe
	versao CDATA #FIXED "2.00"
>
<!ELEMENT vCOFINS (#PCDATA)>
<!ELEMENT vUnTrib (#PCDATA)>
<!ELEMENT verProc (#PCDATA)>
<!ELEMENT xBairro (#PCDATA)>
<!ELEMENT xMotivo (#PCDATA)>
<!ELEMENT COFINSNT (CST)>
<!ELEMENT X509Data (X509Certificate)>
<!ELEMENT cEANTrib (#PCDATA)>
<!ELEMENT dhRecbto (#PCDATA)>
<!ELEMENT modFrete (#PCDATA)>
<!ELEMENT vBCSTRet (#PCDATA)>
<!ELEMENT verAplic (#PCDATA)>
<!ELEMENT Reference (Transforms, DigestMethod, DigestValue)>
<!ATTLIST Reference
	URI CDATA #REQUIRED
>
<!ELEMENT Signature (SignedInfo, SignatureValue, KeyInfo)>
<!ATTLIST Signature
	xmlns CDATA #FIXED "http://www.w3.org/2000/09/xmldsig#"
>
<!ELEMENT Transform EMPTY>
<!ATTLIST Transform
	Algorithm CDATA #REQUIRED
>
<!ELEMENT enderDest (xLgr, nro, xCpl, xBairro, cMun, xMun, UF, CEP, cPais, xPais, fone)>
<!ELEMENT enderEmit (xLgr, nro, ((xCpl, xBairro, cMun, xMun, UF, CEP, cPais, xPais, fone) | (xBairro, cMun, xMun, UF, CEP, cPais, xPais)))>
<!ELEMENT infAdProd (#PCDATA)>
<!ELEMENT COFINSAliq (CST, vBC, pCOFINS, vCOFINS)>
<!ELEMENT SignedInfo (CanonicalizationMethod, SignatureMethod, Reference)>
<!ELEMENT Transforms (Transform+)>
<!ELEMENT transporta ((CNPJ, xNome, IE, xEnder, xMun, UF) | (xNome, IE))>
<!ELEMENT vICMSSTRet (#PCDATA)>
<!ELEMENT DigestValue (#PCDATA)>
<!ELEMENT DigestMethod EMPTY>
<!ATTLIST DigestMethod
	Algorithm CDATA #FIXED "http://www.w3.org/2000/09/xmldsig#sha1"
>
<!ELEMENT SignatureValue (#PCDATA)>
<!ELEMENT SignatureMethod EMPTY>
<!ATTLIST SignatureMethod
	Algorithm CDATA #FIXED "http://www.w3.org/2000/09/xmldsig#rsa-sha1"
>
<!ELEMENT X509Certificate (#PCDATA)>
<!ELEMENT CanonicalizationMethod EMPTY>
<!ATTLIST CanonicalizationMethod
	Algorithm CDATA #FIXED "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
>

=== rwfazul/nodejs-xml/services/files/nota3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE nfeProc SYSTEM "notas.dtd">
<nfeProc>
	<NFe xmlns="http://www.portalfiscal.inf.br/nfe">
		<infNFe Id="NFe43121143708379008348550010000175441000000010" versao="2.00">
			<ide>
				<cUF>43</cUF>
				<cNF>00000001</cNF>
				<natOp>REMESSA VINCUL.ECF VN</natOp>
				<indPag>0</indPag>
				<mod>55</mod>
				<serie>1</serie>
				<nNF>17544</nNF>
				<dEmi>2012-11-23</dEmi>
				<tpNF>1</tpNF>
				<cMunFG>4314902</cMunFG>
				<tpImp>2</tpImp>
				<tpEmis>1</tpEmis>
				<cDV>0</cDV>
				<tpAmb>1</tpAmb>
				<finNFe>1</finNFe>
				<procEmi>0</procEmi>
				<verProc>NeoGrid NFe 1.9.0.1</verProc>
			</ide>
			<emit>
				<CNPJ>43708379008348</CNPJ>
				<xNome>FAST SHOP S.A.</xNome>
				<xFant>FAST SHOP S.A.</xFant>
				<enderEmit>
					<xLgr>JOAO WALLIG</xLgr>
					<nro>1800</nro>
					<xCpl>210 PISO NP</xCpl>
					<xBairro>PASSO D.AREIA</xBairro>
					<cMun>4314902</cMun>
					<xMun>PORTO ALEGRE</xMun>
					<UF>RS</UF>
					<CEP>91349900</CEP>
					<cPais>1058</cPais>
					<xPais>Brasil</xPais>
					<fone>1132323200</fone>
				</enderEmit>
				<IE>0963395009</IE>
				<CRT>3</CRT>
			</emit>
			<dest>
				<CPF>12345678900</CPF>
				<xNome>GIOVANI LIBRELOTTO</xNome>
				<enderDest>
					<xLgr>AV RORAIMA</xLgr>
					<nro>1000</nro>
					<xCpl>SALA 387</xCpl>
					<xBairro>CAMOBI</xBairro>
					<cMun>4316907</cMun>
					<xMun>SANTA MARIA</xMun>
					<UF>RS</UF>
					<CEP>97010041</CEP>
					<cPais>1058</cPais>
					<xPais>Brasil</xPais>
					<fone>5591234567</fone>
				</enderDest>
				<IE>ISENTO</IE>
				<email>librelotto@mail.com</email>
			</dest>
			<entrega>
				<CPF>12345678900</CPF>
				<xLgr>AV RORAIMA</xLgr>
				<nro>1000</nro>
				<xCpl>SALA 387</xCpl>
				<xBairro>CAMOBI</xBairro>
				<cMun>4316907</cMun>
				<xMun>SANTA MARIA</xMun>
				<UF>RS</UF>
			</entrega>
			<det nItem="1">
				<prod>
					<cProd>AEMC838BEA</cProd>
					<cEAN>0885909453498</cEAN>
					<xProd>CABO DE CONEXAO HDMI PRETO | 0885909453498| Rua: A</xProd>
					<NCM>85444200</NCM>
					<CFOP>5929</CFOP>
					<uCom>PC</uCom>
					<qCom>1.0000</qCom>
					<vUnCom>47.0000</vUnCom>
					<vProd>47.00</vProd>
					<cEANTrib>0885909453498</cEANTrib>
					<uTrib>PC</uTrib>
					<qTrib>1.0000</qTrib>
					<vUnTrib>47.0000</vUnTrib>
					<indTot>1</indTot>
				</prod>
				<imposto>
					<ICMS>
						<ICMS60>
							<orig>2</orig>
							<CST>60</CST>
							<vBCSTRet>46.41</vBCSTRet>
							<vICMSSTRet>1.67</vICMSSTRet>
						</ICMS60>
					</ICMS>
					<PIS>
						<PISNT>
							<CST>08</CST>
						</PISNT>
					</PIS>
					<COFINS>
						<COFINSNT>
							<CST>08</CST>
						</COFINSNT>
					</COFINS>
				</imposto>
			</det>
			<total>
				<ICMSTot>
					<vBC>0.00</vBC>
					<vICMS>0.00</vICMS>
					<vBCST>0.00</vBCST>
					<vST>0.00</vST>
					<vProd>47.00</vProd>
					<vFrete>0.00</vFrete>
					<vSeg>0.00</vSeg>
					<vDesc>0.00</vDesc>
					<vII>0.00</vII>
					<vIPI>0.00</vIPI>
					<vPIS>0.00</vPIS>
					<vCOFINS>0.00</vCOFINS>
					<vOutro>0.00</vOutro>
					<vNF>47.00</vNF>
				</ICMSTot>
			</total>
			<transp>
				<modFrete>9</modFrete>
				<vol>
					<qVol>1</qVol>
					<esp>volume</esp>
					<pesoL>0.070</pesoL>
					<pesoB>0.070</pesoB>
				</vol>
			</transp>
			<infAdic>
				<infCpl>Pedido: 35873 Tabela: F8 Vendedor: V104335 Usuario: PATRICED Expedicao:
                    RETIRA PELO CLIENTE Nota Fiscal emitida com base no Cupom fiscal de numero
                    006613 Impressora: C3 Substituicao Trib.ICMS item 1 cf. RICMS Apendice IIObs: G:
                    000 00End.Cobranca: R G: 000 00 Em ate 7 dias apos a entrega, se o produto
                    apresentar defeito, a troca podera ser efetuada diretamente em qualquer das
                    lojas da FAST SHOP no mesmo Estado de emissao do documento fiscal, desde que
                    ausentes avarias ou danos aparentes, sem laudo tecnico ou procedimento de
                    garantia previsto nos artigos 18 a 26 do Codigo de Defesa do Consumidor. A troca
                    se dara mediante apresentacao da nota fiscal, embalagem original e acessorios.
                    Essa troca em 7 dias, nas lojas, e sem maiores formalidades, e um especial
                    beneficio aos nossos clientes, independentemente dos termos e prazos das
                    garantias legal e/ou contratual previstas para o produto/servico (artigos 18 a
                    26 da lei 8.078/90).</infCpl>
			</infAdic>
		</infNFe>
		<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
			<SignedInfo>
				<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
				<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
				<Reference URI="#NFe43121143708379008348550010000175441000000010">
					<Transforms>
						<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
					</Transforms>
					<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
					<DigestValue>kEaUniFxfvNiekrLwRgFkt7zs2E=</DigestValue>
				</Reference>
			</SignedInfo>
			<SignatureValue>szfr1ofW0cIA5cpXEqUpfc3q3psfA0utdS8j3/MWbPVu4nufk//0c/YMZx7WOPt23CVyRHzSgtESuRJ9YS4UKWLY506Rh17lEL3Lytive3hkYi3AVCHWs1HLjN7+SiIZiHFA3XhuVeWT1pibh4lEh0+ElIIxITiB5m8zzDXcgSbPH/3M3lthzHveK/cX1WSrEwub3wjR+hM7Bjw+GDsCev8H9KCobuqP/vIGmJbnrgpe6pZwwpSQGyyQB2cMhfvBalQ50swp+goO7hGKn8pht4sVN4EF34hzzDOuRiH27p7XTzvYTzDmGe6jIikadiWbDDGvlNJFWk7oKTSyBjdjYg==</SignatureValue>
			<KeyInfo>
				<X509Data>
					<X509Certificate>MIIIQjCCBiqgAwIBAgIQDm0R6qTsIXspQjoXR5Z33TANBgkqhkiG9w0BAQsFADB0MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDEtMCsGA1UECxMkQ2VydGlzaWduIENlcnRpZmljYWRvcmEgRGlnaXRhbCBTLkEuMSEwHwYDVQQDExhBQyBDZXJ0aXNpZ24gTXVsdGlwbGEgRzUwHhcNMTIwODI4MDAwMDAwWhcNMTMwODI3MjM1OTU5WjCB0DELMAkGA1UEBhMCQlIxEzARBgNVBAoUCklDUC1CcmFzaWwxODA2BgNVBAsUL0F1dGVudGljYWRvIHBvciBDZXJ0aXNpZ24gQ2VydGlmaWNhZG9yYSBEaWdpdGFsMRswGQYDVQQLFBJBc3NpbmF0dXJhIFRpcG8gQTExFTATBgNVBAsUDElEIC0gMzU0NDQwMzEWMBQGA1UEAxMNRmFzdCBTaG9wIFMgQTEmMCQGCSqGSIb3DQEJARYXaW5mcmF0aUBmYXN0c2hvcC5jb20uYnIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8DuxgkTaOwF4ibXU2Z43Po6bYOfeLwWQxlrv8wNnwgCtXYw8EdIIda+JB3sPhA8QH1ld9XFCw4r+UC1EBppNJVRdAcn9LNUxC6zzka7CLPtDRXw12a+dh2AhSehMGGOs9mTTMo4z3osAheckv4Z1N3doEJgHy9YbJyV52+546KGs3/SjwEelxP04Rb3qtADqXdfRL6R+v6v/DfePWjH/5RQdi8JVJZKhf6qGWfYGLBfjutZc7JSr1CUEiffTNXptrTGkZmvkMJ809LQGvGSIrJ4CpJGmf1DWn0P46Npd90NkTBVvC+c5jZZ9jTLtXBXMb6Yp1Ry9WvzXotumq8f/xAgMBAAGjggNxMIIDbTCBtwYDVR0RBIGvMIGsoDgGBWBMAQMEoC8ELTAyMDMxOTU2MDAxNzk5MjM4OTcwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMKAjBgVgTAEDAqAaBBhNSUxUT04gS0FaVVlVS0kgS0FLVU1PVE+gGQYFYEwBAwOgEAQONDM3MDgzNzkwMDAxMDCgFwYFYEwBAwegDgQMMDAwMDAwMDAwMDAwgRdpbmZyYXRpQGZhc3RzaG9wLmNvbS5icjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFJ1Qz73/JMqvsTPrF+JCeo5pKo5TMA4GA1UdDwEB/wQEAwIF4DCBiQYDVR0gBIGBMH8wfQYGYEwBAgELMHMwcQYIKwYBBQUHAgEWZWh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL0FDX0NlcnRpc2lnbl9NdWx0aXBsYS9EUENfQUNfQ2VydGlTaWduTXVsdGlwbGEucGRmMIIBJQYDVR0fBIIBHDCCARgwXKBaoFiGVmh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL0FDQ2VydGlzaWduTXVsdGlwbGFHNS9MYXRlc3RDUkwuY3JsMFugWaBXhlVodHRwOi8vaWNwLWJyYXNpbC5vdXRyYWxjci5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL0FDQ2VydGlzaWduTXVsdGlwbGFHNS9MYXRlc3RDUkwuY3JsMFugWaBXhlVodHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvQ2VydGlzaWduL0FDQ2VydGlzaWduTXVsdGlwbGFHNS9MYXRlc3RDUkwuY3JsMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBoAYIKwYBBQUHAQEEgZMwgZAwZAYIKwYBBQUHMAKGWGh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vY2VydGlmaWNhZG9zL0FDX0NlcnRpc2lnbl9NdWx0aXBsYV9HNS5wN2MwKAYIKwYBBQUHMAGGHGh0dHA6Ly9vY3NwLmNlcnRpc2lnbi5jb20uYnIwDQYJKoZIhvcNAQELBQADggIBACl4Y5pqf5tvgXmcWYuWVMB5CnF8QUzYTMzIr6OcHJthybSjHCwNvKTY1jSeq2rqW/SuagkjuwTNrIGcY+4QYhb+gkc4z0dEtPcwCcrBSOSwYQ0cl5Q07+VD3crCUpoP14wKHJpzE3CW5n2MrK9rz326LD0UaVGV3yUChi5FjvyKW0/FqDmmRacbR1Z0RsZ5/upln8jDmC7lJv4QQh3mFQCzivLlrSuTztPRocwPpGi7a5edCgKhxiYddLPPPuuE70PtFYlSXOCc12GjXuD5cDEsA+kGDXpB2sG4Q1r/KFcnwMz1KdvY70+WaiJ4ygvSRkj+XA72EjPj1bhBwybOG4Fu/uGWOTslpf2p88UjH4Bk4XnFtU/EaP51DEeoW+R84DaTd13Doi5Ba+SN1X27wFG34RfMUEc8GqIamZdAuRgg8wbrhcU2cpEi80paqCWTvIGf9jEt8rWZHgl/gFf+e1Rv4iLnJliVZquSUr/hI324F7Q2tYpQqmhAbZvMn4gTP00FVF2aMQgYtJEJNjH2NkV4ZONCXs7z+7YI9FfHc11KLu/N0KybzfIHSeiS/SUfkqi3yvHW2Oo+VLrX/vbO+c+5BT3IHoWQimeN7LJzi5pkpXVXHFZcEinpECTFH30rL7HY3ndUTHGg/ktHlXUuNoE1jM/y5Wi9X3nOHkRoUKL6</X509Certificate>
				</X509Data>
			</KeyInfo>
		</Signature>
	</NFe>
	<protNFe versao="2.00">
		<infProt>
			<tpAmb>1</tpAmb>
			<verAplic>5.0</verAplic>
			<chNFe>43121143708379008348550010000175441000000010</chNFe>
			<dhRecbto>2012-11-23T21:16:40</dhRecbto>
			<nProt>143120163710296</nProt>
			<digVal>kEaUniFxfvNiekrLwRgFkt7zs2E=</digVal>
			<cStat>100</cStat>
			<xMotivo>Autorizado o uso da NF-e</xMotivo>
		</infProt>
	</protNFe>
</nfeProc>
